### ISSUE TITLE
Questions about the BlockInst

### ISSUE THREAD

**Issue by JustinWeidlich** [arjunr2/wasm-instrument#4]
Hi there, first of all, thank you for providing this great API.
I have a question regarding the parameter of BlockInst.
I took a look at your r3_record.cpp, and it appears that you are using the function signature's index. I've created my own little function to experiment with, but I'm not getting the same results as you did.
I want to create an unconditional block. The only way I've been able to achieve this is by using BlockInst(2), but I'm unsure why.
Another example would be that, BlockInst(0) results in a 'block (result i32)'.
My function accepts two I32 parameters, returns an I32, and uses three local variables. Any insight would be appreciated.

Thank you in advance!

**Comment by arjunr2** [comment]
Hello,

I'm unsure what you mean by an unconditional block, but I can generally answer how you use the different cases of BlockInst. Blockinst is basically encoded as a signed-64 to account for the union of types it supports.

1. For an empty block, use `BlockInst(-0x40)` or equivalently `BlockInst(-64)`.
2. For a valtype format stored in some variable `uint32 valtype`, use `BlockInst(-valtype)`.
3. For the function signature format stored in `uint32_t sig_idx`, use `BlockInst(+sig_idx)`.

If your use case is a block with type [i32 i32] --> [i32], you need to use format (3) with the respective signature index

**Comment by JustinWeidlich** [comment]
Thank you, those were exactly the answers I was looking for :)
